services:
  teltonika-flespi-telegram-bot:
    build: .
    container_name: teltonika-flespi-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
